### ISSUE TITLE
400 bad request on upload

### ISSUE THREAD

**Issue by ondrejrohon** [rwatts3/orionjs-cloudinary#4]
Hi,

I'm getting this error when trying to upload an image:
400 (Bad Request)

You can see that there is wrong post url, there is missing cloud_name in config.
https://api.cloudinary.com/v1_1//image/upload

I double checked and correct cloud_name is in my orion config. (Checked in DB)
Any idea what might be wrong?

Thanks

**Comment by romans127** [comment]
Interesting. 

Sorry for such a late response. 
Are you still having this issue ?

**Comment by romans127** [comment]
Closing, will re-open if issue persists.
